import "@/app/globals.css";
import type {Metadata} from "next";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import React, {Suspense} from "react";
import AuthProvider from "@/app/context/client-provider";
import {getServerSession} from "next-auth";
import Loading from "@/app/(main)/loading";
import {authOptions} from "@/lib/authOption";


export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    const session = await getServerSession(authOptions)

    return (
        <html lang="en">
        <body>
        <StyledComponentsRegistry>
            <AuthProvider session={session}>
                <Suspense fallback={<Loading/>} >
                        {
                            children
                        }
                </Suspense>
            </AuthProvider>
        </StyledComponentsRegistry>

        </body>
        </html>
    )
}
